-- MySQL Script generated by MySQL Workbench
-- 09/23/15 12:41:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema open_crip
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `open_crip` ;

-- -----------------------------------------------------
-- Schema open_crip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `open_crip` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `open_crip` ;

-- -----------------------------------------------------
-- Table `open_crip`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Client` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `prenom` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_crip`.`Fournisseur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Fournisseur` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Fournisseur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_enseigne` VARCHAR(45) NULL,
  `chiffre_affaire` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_crip`.`Paiement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Paiement` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Paiement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_paiement` DATE NULL,
  `mode_paiement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_crip`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Commande` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prix_total` DECIMAL(10,2) NULL,
  `date_commande` DATE NULL COMMENT 'Date avec heure minute',
  `date_validation` DATE NULL,
  `id_client` INT NOT NULL,
  `id_paiement` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Commande_Client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `open_crip`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Paiement1`
    FOREIGN KEY (`id_paiement`)
    REFERENCES `open_crip`.`Paiement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_id_commande_id_client` ON `open_crip`.`Commande` (`id_client` ASC);

CREATE INDEX `fk_id_commande_id_paiement` ON `open_crip`.`Commande` (`id_paiement` ASC);


-- -----------------------------------------------------
-- Table `open_crip`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Produit` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Produit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference_produit` VARCHAR(45) NULL,
  `prix_unitaire` DECIMAL(10,2) NULL,
  `id_fournisseur` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Produit_Fournisseur1`
    FOREIGN KEY (`id_fournisseur`)
    REFERENCES `open_crip`.`Fournisseur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produit_Fournisseur1_idx` ON `open_crip`.`Produit` (`id_fournisseur` ASC);


-- -----------------------------------------------------
-- Table `open_crip`.`CommandeProduit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`CommandeProduit` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`CommandeProduit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prix_unitaire` DECIMAL(10,2) NOT NULL,
  `quantite` INT NOT NULL,
  `id_commande` INT NOT NULL,
  `id_produit` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Commande_has_Produit_Commande1`
    FOREIGN KEY (`id_commande`)
    REFERENCES `open_crip`.`Commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Produit_Produit1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `open_crip`.`Produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_id_produit` ON `open_crip`.`CommandeProduit` (`id_produit` ASC);

CREATE INDEX `fk_id_commande` ON `open_crip`.`CommandeProduit` (`id_commande` ASC);


-- -----------------------------------------------------
-- Table `open_crip`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(10) NULL,
  `adresse_1` VARCHAR(150) NULL,
  `adresse_2` VARCHAR(150) NULL,
  `code_postal` VARCHAR(10) NULL,
  `ville` VARCHAR(150) NULL,
  `pays` VARCHAR(150) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_crip`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_crip`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `open_crip`.`Utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifiant` VARCHAR(150) NULL,
  `mot_de_passe` VARCHAR(150) NULL,
  `email` VARCHAR(150) NULL,
  `telephone` VARCHAR(45) NULL,
  `date_inscription` DATE NULL,
  `date_derniere_connexion` TIMESTAMP NULL,
  `id_adresse` INT NOT NULL,
  `id_client` INT NULL,
  `id_fournisseur` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Utilisateur_Fournisseur1`
    FOREIGN KEY (`id_fournisseur`)
    REFERENCES `open_crip`.`Fournisseur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `open_crip`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Adresse1`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `open_crip`.`Adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_id_utilisateur_id_fournisseur` ON `open_crip`.`Utilisateur` (`id_fournisseur` ASC);

CREATE INDEX `fk_id_utilisateur_id_client` ON `open_crip`.`Utilisateur` (`id_client` ASC);

CREATE INDEX `fk_id_utilisateur_id_adresse` ON `open_crip`.`Utilisateur` (`id_adresse` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
